<a href="https://colab.research.google.com/github/Himanshu3557/himanshu3557/blob/main/Practice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
"hello"

'hello'

In [ ]:
x=10
type(x)

int

In [ ]:
text="data"
number=42
7%6

1

In [ ]:
2+2
6**2
3>4
4==4

True

In [ ]:
number=[32,34,432]
number[0]

32

In [ ]:
for n in number:
  print(n)

32
34
432

In [ ]:
number.append(80)

print (number)

[32, 34, 432, 90, 90, 6, 80, 80]

In [ ]:
translation={'one':'first','two':'second'}
translation['one']

'first'

In [ ]:
translation['one']='1'
print (translation)

{'one': '1', 'two': 'second'}

In [ ]:
translation['two']=2
print(translation)

{'one': '1', 'two': 2}

In [ ]:
translation['three']=3
print(translation)

{'one': '1', 'two': 2, 'three': 3}

In [ ]:
for year in range (2000, 2030):
  if year% 4==0 and (year%100 !=0 or year%400==0):
    print(year)

2000
2004
2008
2012
2016
2020
2024
2028

In [ ]:
for i in range(0,30):
  if i % 2==0:
    print(i)

0
2
4
6
8
10
12
14
16
18
20
22
24
26
28

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [ ]:
import pandas as pd
pd.read_csv("/content/drive/MyDrive/fifa_world_cup_2026_player_performance.csv")

,player_id,player_name,age,nationality,team,jersey_number,position,height_cm,weight_kg,preferred_foot,...,possession_impact,pressure_resistance,creativity_score,consistency_score,clutch_performance_score,total_goals_tournament,total_assists_tournament,total_minutes_tournament,player_of_match_awards,tournament_rating
0,P00055,Rodri Fati,26,Spanish,Spain,3,Goalkeeper,195,75,Left,...,1.1,44.2,55.9,42.0,51.8,0,0,242,0,5.8
1,P00070,Ansu Le Normand,19,Spanish,Spain,18,Midfielder,178,75,Right,...,3.5,38.2,43.7,31.1,52.7,0,3,342,0,5.5
2,P00066,Gavi Ramos,18,Spanish,Spain,14,Midfielder,177,72,Left,...,15.3,99.0,99.0,83.4,54.8,1,1,245,0,8.4
3,P00073,Pedro Cubarsi,20,Spanish,Spain,21,Forward,182,74,Right,...,1.2,19.8,42.3,40.9,78.5,5,3,422,0,6.7
4,P00059,Alvaro Oyarzabal,23,Spanish,Spain,7,Defender,191,81,Left,...,6.2,44.1,33.5,60.0,56.6,0,0,440,0,5.7
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
54595,P00996,Amir Younis,28,Iraqi,Iraq,8,Defender,177,73,Right,...,0.0,41.9,27.7,31.3,40.5,1,0,97,0,0.0
54596,P01006,Safaa Al-Khafaji,20,Iraqi,Iraq,18,Midfielder,176,72,Right,...,0.0,64.2,53.1,64.8,64.3,2,0,206,0,0.0
54597,P01008,Ahmed Hussein,26,Iraqi,Iraq,20,Midfielder,173,77,Left,...,0.0,75.4,55.0,65.0,64.5,1,1,359,0,0.0
54598,P00991,Ibrahim Mhawi,30,Iraqi,Iraq,3,Goalkeeper,190,81,Right,...,0.0,96.3,39.6,99.0,99.0,0,0,342,0,0.0
54599,P00989,Mohannad Hussein,27,Iraqi,Iraq,1,Goalkeeper,187,73,Right,...,0.0,99.0,34.1,99.0,99.0,0,0,286,0,0.0

In [ ]:
dataframe= pd.read_csv("/content/drive/MyDrive/fifa_world_cup_2026_player_performance.csv")
dataframe

,player_id,player_name,age,nationality,team,jersey_number,position,height_cm,weight_kg,preferred_foot,...,possession_impact,pressure_resistance,creativity_score,consistency_score,clutch_performance_score,total_goals_tournament,total_assists_tournament,total_minutes_tournament,player_of_match_awards,tournament_rating
0,P00055,Rodri Fati,26,Spanish,Spain,3,Goalkeeper,195,75,Left,...,1.1,44.2,55.9,42.0,51.8,0,0,242,0,5.8
1,P00070,Ansu Le Normand,19,Spanish,Spain,18,Midfielder,178,75,Right,...,3.5,38.2,43.7,31.1,52.7,0,3,342,0,5.5
2,P00066,Gavi Ramos,18,Spanish,Spain,14,Midfielder,177,72,Left,...,15.3,99.0,99.0,83.4,54.8,1,1,245,0,8.4
3,P00073,Pedro Cubarsi,20,Spanish,Spain,21,Forward,182,74,Right,...,1.2,19.8,42.3,40.9,78.5,5,3,422,0,6.7
4,P00059,Alvaro Oyarzabal,23,Spanish,Spain,7,Defender,191,81,Left,...,6.2,44.1,33.5,60.0,56.6,0,0,440,0,5.7
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
54595,P00996,Amir Younis,28,Iraqi,Iraq,8,Defender,177,73,Right,...,0.0,41.9,27.7,31.3,40.5,1,0,97,0,0.0
54596,P01006,Safaa Al-Khafaji,20,Iraqi,Iraq,18,Midfielder,176,72,Right,...,0.0,64.2,53.1,64.8,64.3,2,0,206,0,0.0
54597,P01008,Ahmed Hussein,26,Iraqi,Iraq,20,Midfielder,173,77,Left,...,0.0,75.4,55.0,65.0,64.5,1,1,359,0,0.0
54598,P00991,Ibrahim Mhawi,30,Iraqi,Iraq,3,Goalkeeper,190,81,Right,...,0.0,96.3,39.6,99.0,99.0,0,0,342,0,0.0
54599,P00989,Mohannad Hussein,27,Iraqi,Iraq,1,Goalkeeper,187,73,Right,...,0.0,99.0,34.1,99.0,99.0,0,0,286,0,0.0

In [ ]:
dataframe.head()
dataframe

,player_id,player_name,age,nationality,team,jersey_number,position,height_cm,weight_kg,preferred_foot,...,possession_impact,pressure_resistance,creativity_score,consistency_score,clutch_performance_score,total_goals_tournament,total_assists_tournament,total_minutes_tournament,player_of_match_awards,tournament_rating
0,P00055,Rodri Fati,26,Spanish,Spain,3,Goalkeeper,195,75,Left,...,1.1,44.2,55.9,42.0,51.8,0,0,242,0,5.8
1,P00070,Ansu Le Normand,19,Spanish,Spain,18,Midfielder,178,75,Right,...,3.5,38.2,43.7,31.1,52.7,0,3,342,0,5.5
2,P00066,Gavi Ramos,18,Spanish,Spain,14,Midfielder,177,72,Left,...,15.3,99.0,99.0,83.4,54.8,1,1,245,0,8.4
3,P00073,Pedro Cubarsi,20,Spanish,Spain,21,Forward,182,74,Right,...,1.2,19.8,42.3,40.9,78.5,5,3,422,0,6.7
4,P00059,Alvaro Oyarzabal,23,Spanish,Spain,7,Defender,191,81,Left,...,6.2,44.1,33.5,60.0,56.6,0,0,440,0,5.7
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
54595,P00996,Amir Younis,28,Iraqi,Iraq,8,Defender,177,73,Right,...,0.0,41.9,27.7,31.3,40.5,1,0,97,0,0.0
54596,P01006,Safaa Al-Khafaji,20,Iraqi,Iraq,18,Midfielder,176,72,Right,...,0.0,64.2,53.1,64.8,64.3,2,0,206,0,0.0
54597,P01008,Ahmed Hussein,26,Iraqi,Iraq,20,Midfielder,173,77,Left,...,0.0,75.4,55.0,65.0,64.5,1,1,359,0,0.0
54598,P00991,Ibrahim Mhawi,30,Iraqi,Iraq,3,Goalkeeper,190,81,Right,...,0.0,96.3,39.6,99.0,99.0,0,0,342,0,0.0
54599,P00989,Mohannad Hussein,27,Iraqi,Iraq,1,Goalkeeper,187,73,Right,...,0.0,99.0,34.1,99.0,99.0,0,0,286,0,0.0

In [ ]:
dataframe.tail()
dataframe

,player_id,player_name,age,nationality,team,jersey_number,position,height_cm,weight_kg,preferred_foot,...,possession_impact,pressure_resistance,creativity_score,consistency_score,clutch_performance_score,total_goals_tournament,total_assists_tournament,total_minutes_tournament,player_of_match_awards,tournament_rating
0,P00055,Rodri Fati,26,Spanish,Spain,3,Goalkeeper,195,75,Left,...,1.1,44.2,55.9,42.0,51.8,0,0,242,0,5.8
1,P00070,Ansu Le Normand,19,Spanish,Spain,18,Midfielder,178,75,Right,...,3.5,38.2,43.7,31.1,52.7,0,3,342,0,5.5
2,P00066,Gavi Ramos,18,Spanish,Spain,14,Midfielder,177,72,Left,...,15.3,99.0,99.0,83.4,54.8,1,1,245,0,8.4
3,P00073,Pedro Cubarsi,20,Spanish,Spain,21,Forward,182,74,Right,...,1.2,19.8,42.3,40.9,78.5,5,3,422,0,6.7
4,P00059,Alvaro Oyarzabal,23,Spanish,Spain,7,Defender,191,81,Left,...,6.2,44.1,33.5,60.0,56.6,0,0,440,0,5.7
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
54595,P00996,Amir Younis,28,Iraqi,Iraq,8,Defender,177,73,Right,...,0.0,41.9,27.7,31.3,40.5,1,0,97,0,0.0
54596,P01006,Safaa Al-Khafaji,20,Iraqi,Iraq,18,Midfielder,176,72,Right,...,0.0,64.2,53.1,64.8,64.3,2,0,206,0,0.0
54597,P01008,Ahmed Hussein,26,Iraqi,Iraq,20,Midfielder,173,77,Left,...,0.0,75.4,55.0,65.0,64.5,1,1,359,0,0.0
54598,P00991,Ibrahim Mhawi,30,Iraqi,Iraq,3,Goalkeeper,190,81,Right,...,0.0,96.3,39.6,99.0,99.0,0,0,342,0,0.0
54599,P00989,Mohannad Hussein,27,Iraqi,Iraq,1,Goalkeeper,187,73,Right,...,0.0,99.0,34.1,99.0,99.0,0,0,286,0,0.0

In [ ]:
type(dataframe)

pandas.core.frame.DataFrame

In [ ]:
dataframe.dtypes

player_id                    object
player_name                  object
age                           int64
nationality                  object
team                         object
                             ...
total_goals_tournament        int64
total_assists_tournament      int64
total_minutes_tournament      int64
player_of_match_awards        int64
tournament_rating           float64
Length: 75, dtype: object

In [ ]:
print(dataframe[["player_name","position"]])

            player_name    position
0            Rodri Fati  Goalkeeper
1       Ansu Le Normand  Midfielder
2            Gavi Ramos  Midfielder
3         Pedro Cubarsi     Forward
4      Alvaro Oyarzabal    Defender
...                 ...         ...
54595       Amir Younis    Defender
54596  Safaa Al-Khafaji  Midfielder
54597     Ahmed Hussein  Midfielder
54598     Ibrahim Mhawi  Goalkeeper
54599  Mohannad Hussein  Goalkeeper

[54600 rows x 2 columns]

In [ ]:
dataframe.shape

(54600, 75)

In [ ]:
pd.unique(dataframe['player_id'])

array(['P00055', 'P00070', 'P00066', ..., 'P00326', 'P00313', 'P00314'],
      dtype=object)

In [2]:
import numpy as np
a=np.array([1,5,6,9,10])
print(a)

[ 1  5  6  9 10]

In [ ]:
b=np.array((10,20,30))

In [7]:
a=np.array([[1,2,3],
           [ 4,5,6]])

In [9]:
print(a.shape)

(2, 3)

In [8]:
print(a.size)

6

In [3]:
np.arange(12)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [10]:
a=np.array([10,20,30,40,50])
a[1:4]

array([20, 30, 40])

In [11]:
a=np.array([1,2,3])
a+10

array([11, 12, 13])

In [12]:
from google.colab import drive
drive.mount('/gdrive')

Mounted at /gdrive

In [13]:
a=np.array([2,3,6,8])
res=np.mean(a)
print(res)
result=np.sum(a)
print(result)

4.75
19

In [14]:
a=np.array([7,2,8,1])
np.sort(a)

array([1, 2, 7, 8])

In [18]:
a=np.array([10,20,30,20])
np.where(a==20)

(array([1, 3]),)

In [19]:
a=np.array([1,2,3,4,5,6])
a[a%2==0]

array([2, 4, 6])

In [20]:
a=np.array([1,2,3,4,5,6])
np.split(a,3)

[array([1, 2]), array([3, 4]), array([5, 6])]

In [27]:
for num in range(1, 100):
    is_prime = True

    for i in range(2, int(num**0.5) + 1):
        if num % i == 0:
            is_prime = False
            break

    if is_prime:
        print(num, end=" ")

1 2 3 5 7 11 13 17 19 23 29 31 37 41 43 47 53 59 61 67 71 73 79 83 89 97

In [57]:
import pandas as pd
df1 = pd.read_csv('/content/drive/MyDrive/dataset1.csv')
df2 = pd.read_csv('/content/drive/MyDrive/dataset2.csv')
df1.head(12)

,Student_ID,Name,Gender,Age,City,Department,Semester,Maths,Science,English,Attendance,Fees,Placement
0,101,Rahul,Male,20,Delhi,Btech,2,85.0,78.0,90.0,92.0,50000.0,Yes
1,102,Priya,Female,21,Mumbai,BCA,2,76.0,88.0,84.0,95.0,52000.0,No
2,103,Amit,Male,22,Delhi,Btech,4,92.0,91.0,89.0,88.0,60000.0,Yes
3,104,Neha,Female,20,Pune,BBA,2,65.0,72.0,80.0,90.0,45000.0,No
4,105,Rohan,Male,23,Delhi,MCA,4,81.0,85.0,NaN,87.0,61000.0,Yes
5,106,Anjali,Female,21,Mumbai,BCA,2,90.0,95.0,94.0,98.0,55000.0,Yes
6,107,Karan,Male,22,Pune,BBA,4,70.0,68.0,75.0,NaN,47000.0,No
7,108,Sneha,Female,20,Delhi,Btech,4,88.0,90.0,92.0,96.0,62000.0,Yes
8,109,Vikas,Male,21,Lucknow,BCA,2,60.0,65.0,70.0,80.0,48000.0,No
9,110,Pooja,Female,22,Delhi,MCA,4,95.0,96.0,98.0,99.0,65000.0,Yes
10,111,Arjun,Male,20,Jaipur,BCA,2,82.0,79.0,NaN,91.0,51000.0,No
11,112,Kriti,Female,21,Mumbai,Btech,4,91.0,89.0,90.0,97.0,NaN,Yes

In [82]:
merging=pd.merge(df1,df2,on="Student_ID")
merging

,Student_ID,Name,Gender,Age,City,Department,Semester,Maths,Science,English,Attendance,Fees,Placement,Company,Package_LPA
0,101,Rahul,Male,20,Delhi,Btech,2,85.0,78.0,90.0,92.0,50000.0,Yes,TCS,4.5
1,103,Amit,Male,22,Delhi,Btech,4,92.0,91.0,89.0,88.0,60000.0,Yes,Infosys,5.2
2,105,Rohan,Male,23,Delhi,MCA,4,81.0,85.0,NaN,87.0,61000.0,Yes,Accenture,6.0
3,106,Anjali,Female,21,Mumbai,BCA,2,90.0,95.0,94.0,98.0,55000.0,Yes,Capgemini,5.0
4,108,Sneha,Female,20,Delhi,Btech,4,88.0,90.0,92.0,96.0,62000.0,Yes,Google,18.0
5,110,Pooja,Female,22,Delhi,MCA,4,95.0,96.0,98.0,99.0,65000.0,Yes,Microsoft,24.0
6,112,Kriti,Female,21,Mumbai,Btech,4,91.0,89.0,90.0,97.0,NaN,Yes,Amazon,20.0
7,115,Deepak,Male,23,Lucknow,Btech,4,NaN,93.0,91.0,94.0,64000.0,Yes,Wipro,4.2

In [61]:
df.head()

   Student_ID    Company  Package_LPA
0         101        TCS          4.5
1         103    Infosys          5.2
2         105  Accenture          6.0
3         106  Capgemini          5.0
4         108     Google         18.0

In [70]:
kk=pd.concat([df1,df2],axis=1)
kk

,Student_ID,Name,Gender,Age,City,Department,Semester,Maths,Science,English,Attendance,Fees,Placement,Student_ID,Company,Package_LPA
0,101,Rahul,Male,20,Delhi,Btech,2,85.0,78.0,90.0,92.0,50000.0,Yes,101.0,TCS,4.5
1,102,Priya,Female,21,Mumbai,BCA,2,76.0,88.0,84.0,95.0,52000.0,No,103.0,Infosys,5.2
2,103,Amit,Male,22,Delhi,Btech,4,92.0,91.0,89.0,88.0,60000.0,Yes,105.0,Accenture,6.0
3,104,Neha,Female,20,Pune,BBA,2,65.0,72.0,80.0,90.0,45000.0,No,106.0,Capgemini,5.0
4,105,Rohan,Male,23,Delhi,MCA,4,81.0,85.0,NaN,87.0,61000.0,Yes,108.0,Google,18.0
5,106,Anjali,Female,21,Mumbai,BCA,2,90.0,95.0,94.0,98.0,55000.0,Yes,110.0,Microsoft,24.0
6,107,Karan,Male,22,Pune,BBA,4,70.0,68.0,75.0,NaN,47000.0,No,112.0,Amazon,20.0
7,108,Sneha,Female,20,Delhi,Btech,4,88.0,90.0,92.0,96.0,62000.0,Yes,115.0,Wipro,4.2
8,109,Vikas,Male,21,Lucknow,BCA,2,60.0,65.0,70.0,80.0,48000.0,No,NaN,NaN,NaN
9,110,Pooja,Female,22,Delhi,MCA,4,95.0,96.0,98.0,99.0,65000.0,Yes,NaN,NaN,NaN
10,111,Arjun,Male,20,Jaipur,BCA,2,82.0,79.0,NaN,91.0,51000.0,No,NaN,NaN,NaN
11,112,Kriti,Female,21,Mumbai,Btech,4,91.0,89.0,90.0,97.0,NaN,Yes,NaN,NaN,NaN
12,113,Manish,Male,22,Delhi,Btech,2,74.0,NaN,82.0,89.0,53000.0,No,NaN,NaN,NaN
13,114,Simran,Female,20,Pune,BBA,2,68.0,71.0,74.0,86.0,46000.0,No,NaN,NaN,NaN
14,115,Deepak,Male,23,Lucknow,Btech,4,NaN,93.0,91.0,94.0,64000.0,Yes,NaN,NaN,NaN

In [71]:
kk.isnull()

,Student_ID,Name,Gender,Age,City,Department,Semester,Maths,Science,English,Attendance,Fees,Placement,Student_ID,Company,Package_LPA
0,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False
5,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
6,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False
7,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
8,False,False,False,False,False,False,False,False,False,False,False,False,False,True,True,True
9,False,False,False,False,False,False,False,False,False,False,False,False,False,True,True,True
10,False,False,False,False,False,False,False,False,False,True,False,False,False,True,True,True
11,False,False,False,False,False,False,False,False,False,False,False,True,False,True,True,True
12,False,False,False,False,False,False,False,False,True,False,False,False,False,True,True,True
13,False,False,False,False,False,False,False,False,False,False,False,False,False,True,True,True
14,False,False,False,False,False,False,False,True,False,False,False,False,False,True,True,True

In [73]:
kk.fillna(0)

,Student_ID,Name,Gender,Age,City,Department,Semester,Maths,Science,English,Attendance,Fees,Placement,Student_ID,Company,Package_LPA
0,101,Rahul,Male,20,Delhi,Btech,2,85.0,78.0,90.0,92.0,50000.0,Yes,101.0,TCS,4.5
1,102,Priya,Female,21,Mumbai,BCA,2,76.0,88.0,84.0,95.0,52000.0,No,103.0,Infosys,5.2
2,103,Amit,Male,22,Delhi,Btech,4,92.0,91.0,89.0,88.0,60000.0,Yes,105.0,Accenture,6.0
3,104,Neha,Female,20,Pune,BBA,2,65.0,72.0,80.0,90.0,45000.0,No,106.0,Capgemini,5.0
4,105,Rohan,Male,23,Delhi,MCA,4,81.0,85.0,0.0,87.0,61000.0,Yes,108.0,Google,18.0
5,106,Anjali,Female,21,Mumbai,BCA,2,90.0,95.0,94.0,98.0,55000.0,Yes,110.0,Microsoft,24.0
6,107,Karan,Male,22,Pune,BBA,4,70.0,68.0,75.0,0.0,47000.0,No,112.0,Amazon,20.0
7,108,Sneha,Female,20,Delhi,Btech,4,88.0,90.0,92.0,96.0,62000.0,Yes,115.0,Wipro,4.2
8,109,Vikas,Male,21,Lucknow,BCA,2,60.0,65.0,70.0,80.0,48000.0,No,0.0,0,0.0
9,110,Pooja,Female,22,Delhi,MCA,4,95.0,96.0,98.0,99.0,65000.0,Yes,0.0,0,0.0
10,111,Arjun,Male,20,Jaipur,BCA,2,82.0,79.0,0.0,91.0,51000.0,No,0.0,0,0.0
11,112,Kriti,Female,21,Mumbai,Btech,4,91.0,89.0,90.0,97.0,0.0,Yes,0.0,0,0.0
12,113,Manish,Male,22,Delhi,Btech,2,74.0,0.0,82.0,89.0,53000.0,No,0.0,0,0.0
13,114,Simran,Female,20,Pune,BBA,2,68.0,71.0,74.0,86.0,46000.0,No,0.0,0,0.0
14,115,Deepak,Male,23,Lucknow,Btech,4,0.0,93.0,91.0,94.0,64000.0,Yes,0.0,0,0.0

In [74]:
kk.dropna()

,Student_ID,Name,Gender,Age,City,Department,Semester,Maths,Science,English,Attendance,Fees,Placement,Student_ID,Company,Package_LPA
0,101,Rahul,Male,20,Delhi,Btech,2,85.0,78.0,90.0,92.0,50000.0,Yes,101.0,TCS,4.5
1,102,Priya,Female,21,Mumbai,BCA,2,76.0,88.0,84.0,95.0,52000.0,No,103.0,Infosys,5.2
2,103,Amit,Male,22,Delhi,Btech,4,92.0,91.0,89.0,88.0,60000.0,Yes,105.0,Accenture,6.0
3,104,Neha,Female,20,Pune,BBA,2,65.0,72.0,80.0,90.0,45000.0,No,106.0,Capgemini,5.0
5,106,Anjali,Female,21,Mumbai,BCA,2,90.0,95.0,94.0,98.0,55000.0,Yes,110.0,Microsoft,24.0
7,108,Sneha,Female,20,Delhi,Btech,4,88.0,90.0,92.0,96.0,62000.0,Yes,115.0,Wipro,4.2

In [78]:
kk["English"].fillna(df1["English"].mean())

0     90.000000
1     84.000000
2     89.000000
3     80.000000
4     85.307692
5     94.000000
6     75.000000
7     92.000000
8     70.000000
9     98.000000
10    85.307692
11    90.000000
12    82.000000
13    74.000000
14    91.000000
Name: English, dtype: float64

In [81]:
df1["Attendance"].fillna(df1["Attendance"].median())

0     92.0
1     95.0
2     88.0
3     90.0
4     87.0
5     98.0
6     91.5
7     96.0
8     80.0
9     99.0
10    91.0
11    97.0
12    89.0
13    86.0
14    94.0
Name: Attendance, dtype: float64